### ISSUE TITLE
configtx - add better profiles support

### ISSUE THREAD

**Issue by Hejwo** [softwaremill/fabrica#18]
Currently all organisations are just added to `AllOrgChannel` profile and then this profile is used to generate ALL channels. Why that's wrong ?  
- we have 3 organisations: `org1`, `org2`, `org3`  
- channel `channel1` defined between `org1`, `org2`  
- `org3` **can just fetch & join channel1** because of `AllOrgChannel` used

**Comment by dzikowski** [comment]
resolved in #162
