### ISSUE TITLE
Don't use pwd in fabrica.sh docker commands

### ISSUE THREAD

**Issue by Hejwo** [softwaremill/fabrica#97]
Valid security issue, using pwd in current dir will pass it's content to docker.  
- [ ] It might be our project's source code or users home.
- [x] this is ambiguous, since different dirs are mounted to /network/target, depending on the command

**Comment by dzikowski** [comment]
perhaps it would be enough to rename `/network/target` to `/fabrica-target` or `/fabrica-workspace`
